/**
 * @file ArcDataInitializer.h
 * @brief 弧数据初始化器声明，继承IDataInitializer
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
