/**
 * @file DataInitializationManager.h
 * @brief 初始化管理器声明，协调所有初始化器
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
