/**
 * @file Arc.h
 * @brief Arc数据模型声明，包含Arc的属性和关系定义
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once
#include <array>
#include <memory>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

#include "Pin.h"  // 引入Pin类定义

namespace dm {
class Arc {
 public:
  std::string name;  // Arc名称
  std::string type;  // Arc类型（如：setup, hold, recovery等）
  std::shared_ptr<Pin> start_pin;  // 起始Pin
  std::shared_ptr<Pin> end_pin;    // 结束Pin
  std::array<double, 2> delay;  // delay_rise, delay_fall, according to end_pin
  // std::vector<std::shared_ptr<Path>> paths;  // 路径列表

 public:
  // nlohmann::json to_json();  // 转换为JSON格式
};
}  // namespace dm
