/**
 * @file Path.h
 * @brief 路径数据模型声明，包含数据结构定义
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

#include "Pin.h"

namespace dm {
class Path {
 public:
  std::string startpoint;
  std::string endpoint;
  std::string group;
  std::string clock;
  double slack;
  std::unordered_map<std::string, double> path_params;
  std::vector<std::shared_ptr<Pin>> path;
  std::optional<double> length;
  std::optional<double> detour;
  std::optional<double> cell_delay_pct;
  std::optional<double> net_delay_pct;

 public:
  double get_length();
  double get_detour();
  double get_cell_delay_pct();
  double get_net_delay_pct();

 private:
  std::optional<double> total_delay;

 private:
  double get_delay();
};
}  // namespace dm
