/**
 * @file Pin.h
 * @brief Pin Net数据模型声明，包含引脚属性定义
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once
#include <memory>
#include <nlohmann/json.hpp>
#include <optional>
#include <string>

#include "yaml-cpp/yaml.h"

namespace dm {
class Net;
class Pin;

class Pin {
 public:
  std::string name;
  std::string cell;
  std::string instance;  // invs only
  double trans;
  double incr_delay;
  double path_delay;
  std::optional<double> pta_buf;
  std::optional<double> pta_net;
  bool rise_fall;
  bool is_input;  // cell input
  std::pair<double, double> location;
  std::shared_ptr<Net> net;

  // TODO: remove type, using db pointer instead
  std::string type;

 public:
  YAML::Node to_yaml();
  nlohmann::json to_json();
};

class Net {
 public:
  std::string name;
  int fanout;
  double cap;
  std::pair<std::shared_ptr<Pin>, std::shared_ptr<Pin>> pins;

 public:
  nlohmann::json to_json();
};
}  // namespace dm
