version: '3.8'

services:
  cpp-build:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./output:/output
    # command: ["/bin/bash", "-c", "cp /output/YourExecutable /output"]
