services:
  cpp-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command:
      - python3
      - ./script/build.py
      - --docker
    # command: ["ls"]
