/**
 * @file DataAccessorFactory.h
 * @brief 数据访问器工厂类声明
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
