/**
 * @file DataAccessorFactory.cpp
 * @brief 实现根据配置创建不同类型的数据访问器，包含单例管理
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "DataAccessorFactory.h"

// TODO: Implement the functionality here
