/**
 * @file RepositoryFactory.h
 * @brief 仓储工厂类声明
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

#include <memory>
#include <string>

#include "dm/interfaces/IRepository.h"

class RepositoryFactory {
 public:
  enum class RepositoryType { PATH_BASED, ARC_BASED };

  // 根据类型创建仓储
  static std::unique_ptr<IRepository> create(RepositoryType type);

 private:
  RepositoryFactory() = default;
};
