/**
 * @file RepositoryFactory.cpp
 * @brief 实现根据配置创建不同类型的仓储，连接池管理、配置解析等
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "RepositoryFactory.h"

#include <stdexcept>

#include "RepositoryFactory.h"
#include "dm/repositories/ArcBasedRepository.h"
#include "dm/repositories/PathBasedRepository.h"

std::unique_ptr<IRepository> RepositoryFactory::create(RepositoryType type) {
  switch (type) {
    case RepositoryType::PATH_BASED:
      return std::make_unique<PathBasedRepository>();
    case RepositoryType::ARC_BASED:
      return std::make_unique<ArcBasedRepository>();
    default:
      throw std::invalid_argument("Unknown repository type");
  }
}
