/**
 * @file PinOnlyDataAdapter.h
 * @brief 引脚数据适配器声明，继承IDataAccessor
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
