/**
 * @file PathBasedRepository.cpp
 * @brief 实现路径数据的增删改查、连接管理、事务处理、文件操作等
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "PathBasedRepository.h"

void PathBasedRepository::add_arc(const dm::Arc &arc) {
  // Path-based repository does not store arcs
  throw std::runtime_error("PathBasedRepository does not support arcs");
}
void PathBasedRepository::add_path(const dm::Path &path) {
  paths_.push_back(path);
}
std::vector<dm::Arc> PathBasedRepository::read_arcs() const {
  // Path-based repository does not store arcs
  throw std::runtime_error("PathBasedRepository does not support arcs");
}
std::vector<dm::Path> PathBasedRepository::read_paths() const { return paths_; }
dm::Arc PathBasedRepository::query_arcs(const dm::Pin &from_pin,
                                        const dm::Pin &to_pin) const {
  // Path-based repository does not store arcs
  throw std::runtime_error("PathBasedRepository does not support arcs");
}
