/**
 * @file PathBasedRepository.h
 * @brief 路径数据库仓储类声明，继承IRepository
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

#include "dm/interfaces/IRepository.h"

class PathBasedRepository : public IRepository {
 public:
  PathBasedRepository() = default;
  ~PathBasedRepository() override = default;

  void add_arc(const dm::Arc &arc) override;
  void add_path(const dm::Path &path) override;
  std::vector<dm::Arc> read_arcs() const override;
  std::vector<dm::Path> read_paths() const override;
  dm::Arc query_arcs(const dm::Pin &from_pin,
                     const dm::Pin &to_pin) const override;

 private:
  std::vector<dm::Path> paths_;
};
