/**
 * @file DataAccessException.h
 * @brief 数据访问异常类声明，继承std::exception
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
