/**
 * @file DataAccessException.cpp
 * @brief 实现不同类型的数据访问异常（连接失败、数据不存在、格式错误等）
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "DataAccessException.h"

// TODO: Implement the functionality here
