/**
 * @file InitializationException.cpp
 * @brief 实现初始化相关异常（依赖失败、配置错误、资源不足等）
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "InitializationException.h"

// TODO: Implement the functionality here
