/**
 * @file IDataInitializer.h
 * @brief 数据初始化器接口，包含初始化、状态检查、依赖管理等方法
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
