/**
 * @file IDataInitializer.cpp
 * @brief 通用初始化逻辑，如状态管理、错误处理等
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#include "IDataInitializer.h"

// TODO: Implement the functionality here
