/**
 * @file IDataAccessor.h
 * @brief 数据访问器接口定义，包含读取、写入、查询等抽象方法
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
