/**
 * @file IRepository.h
 * @brief 数据仓储接口定义，包含CRUD操作、事务管理等抽象方法
 * @author Generated by create_project_structure.sh
 * @date 2025-06-12
 */

#pragma once

// TODO: Implement the interface/class declaration here
